# Generated by Django 5.0.6 on 2024-06-22 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_is_verified_alter_users_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
