# Generated by Django 5.0.6 on 2024-06-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_users_birth_year_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
