# Generated by Django 5.0.6 on 2024-06-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_users_birth_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='birth_year',
            new_name='birth_date',
        ),
    ]
